CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM pg_namespace WHERE nspname = 'settlements') THEN
        CREATE SCHEMA settlements;
    END IF;
END $EF$;

CREATE TABLE settlements."Mvz" (
    "Id" text NOT NULL,
    "MvzCode" text,
    "MvzName" text,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Mvz" PRIMARY KEY ("Id")
);

CREATE TABLE settlements."Reports" (
    "Id" uuid NOT NULL,
    "Name" text,
    "Number" text NOT NULL,
    "ServiceDateFrom" date NOT NULL,
    "ServiceDateTo" date NOT NULL,
    "ServiceCompanySapId" text NOT NULL,
    "ServiceCompanyName" text NOT NULL,
    "ServiceCenterExternalIds" text[] NOT NULL DEFAULT ('{}'),
    "CreatedAt" timestamp with time zone NOT NULL,
    "CreatedBy" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UpdatedBy" text NOT NULL,
    "SentToPaymentDate" timestamp with time zone,
    "PaymentDate" timestamp with time zone,
    "Status" integer NOT NULL,
    "TotalCost" numeric NOT NULL,
    "ItemsCount" integer NOT NULL,
    "PaymentId" uuid,
    CONSTRAINT "PK_Reports" PRIMARY KEY ("Id")
);

CREATE TABLE settlements."ServiceCenters" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ExternalId" text NOT NULL,
    "Name" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "ServiceCompanySapId" text NOT NULL,
    CONSTRAINT "PK_ServiceCenters" PRIMARY KEY ("Id")
);

CREATE TABLE settlements."ServiceCompanies" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "SapId" text NOT NULL,
    "Name" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ServiceCompanies" PRIMARY KEY ("Id")
);

CREATE TABLE settlements."ReportItems" (
    "Id" uuid NOT NULL,
    "CouponNumber" text NOT NULL,
    "SaleOrderNumber" text,
    "OrderNumber" text,
    "ServiceDate" date NOT NULL,
    "SaleDate" timestamp with time zone NOT NULL,
    "ServiceName" text NOT NULL,
    "ServiceCompanySapId" text NOT NULL,
    "ServiceCenterExternalId" text NOT NULL,
    "ServiceCenterName" text NOT NULL,
    "CityKisId" text NOT NULL,
    "CityName" text NOT NULL,
    "ShopName" text NOT NULL,
    "WareCode" text NOT NULL,
    "Cost" numeric NOT NULL,
    "TotalCost" numeric NOT NULL,
    "ReportId" uuid NOT NULL,
    "SearchText" text NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "SapPrice" numeric,
    "SapNds" text,
    "CheckNumber" integer NOT NULL,
    "ConfirmType" integer,
    "BsiStatus" integer NOT NULL,
    "AdditionalServices" jsonb NOT NULL DEFAULT ('[]'::jsonb),
    CONSTRAINT "PK_ReportItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReportItems_Mvz_ShopName" FOREIGN KEY ("ShopName") REFERENCES settlements."Mvz" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReportItems_Reports_ReportId" FOREIGN KEY ("ReportId") REFERENCES settlements."Reports" ("Id") ON DELETE CASCADE
);

CREATE TABLE settlements."Appeals" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CouponNumber" text NOT NULL,
    "SaleOrderNumber" text,
    "OrderNumber" text,
    "Created" timestamp with time zone NOT NULL,
    "SaleDate" timestamp with time zone NOT NULL,
    "ServiceDate" date NOT NULL,
    "WareCode" text NOT NULL,
    "ServiceName" text NOT NULL,
    "ServicePrice" numeric NOT NULL,
    "BrandId" integer NOT NULL,
    "CityKisId" text NOT NULL,
    "CityName" text NOT NULL,
    "ServiceCompanyId" integer NOT NULL,
    "ServiceCenterId" integer NOT NULL,
    "ShopName" text NOT NULL,
    "AdditionalServices" jsonb NOT NULL DEFAULT ('[]'::jsonb),
    "BsiStatus" integer NOT NULL,
    "PaymentStatus" integer NOT NULL,
    "ConfirmType" integer,
    "ProjectTypeId" integer NOT NULL,
    "ReportId" uuid,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "CheckNumber" integer NOT NULL,
    CONSTRAINT "PK_Appeals" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Appeals_ServiceCenters_ServiceCenterId" FOREIGN KEY ("ServiceCenterId") REFERENCES settlements."ServiceCenters" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Appeals_ServiceCompanies_ServiceCompanyId" FOREIGN KEY ("ServiceCompanyId") REFERENCES settlements."ServiceCompanies" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_Appeals_CouponNumber" ON settlements."Appeals" ("CouponNumber");

CREATE INDEX "IX_Appeals_ServiceCenterId" ON settlements."Appeals" ("ServiceCenterId");

CREATE INDEX "IX_Appeals_ServiceCompanyId" ON settlements."Appeals" ("ServiceCompanyId");

CREATE UNIQUE INDEX "IX_ReportItems_CouponNumber" ON settlements."ReportItems" ("CouponNumber");

CREATE INDEX "IX_ReportItems_ReportId_ServiceDate" ON settlements."ReportItems" ("ReportId", "ServiceDate");

CREATE INDEX "IX_ReportItems_ShopName" ON settlements."ReportItems" ("ShopName");

CREATE INDEX "IX_Reports_ServiceCompanySapId_CreatedAt" ON settlements."Reports" ("ServiceCompanySapId", "CreatedAt" DESC);

CREATE UNIQUE INDEX "IX_ServiceCenters_ExternalId" ON settlements."ServiceCenters" ("ExternalId");

CREATE INDEX "IX_ServiceCenters_ServiceCompanySapId" ON settlements."ServiceCenters" ("ServiceCompanySapId");

CREATE UNIQUE INDEX "IX_ServiceCompanies_SapId" ON settlements."ServiceCompanies" ("SapId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260901150201_Initial', '10.0.10');

COMMIT;

