//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ServiceModel;
using System.ServiceModel.Channels;
using System.ServiceModel.Description;
using System.Xml.Schema;
using System.Xml.Serialization;

namespace zmv_ws_get_prices_for_sp_bi
{
    [ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="zmv_ws_get_prices_for_sp_bi.ZMV_WS_GET_PRICES_FOR_SP")]
    public interface ZMV_WS_GET_PRICES_FOR_SP
    {

        [OperationContractAttribute(Action="urn:sap-com:document:sap:rfc:functions:ZMV_WS_GET_PRICES_FOR_SP:ZMV_WS_GET_PRICES_FOR_SPRequest", ReplyAction="*")]
        [XmlSerializerFormatAttribute(SupportFaults=true)]
        Task<ZMV_WS_GET_PRICES_FOR_SPResponse1> ZMV_WS_GET_PRICES_FOR_SPAsync(ZMV_WS_GET_PRICES_FOR_SPRequest request);
    }

    [XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMV_WS_GET_PRICES_FOR_SP1
    {
        [XmlArrayAttribute(Form=XmlSchemaForm.Unqualified, Order=0)]
        [XmlArrayItemAttribute("item", Form=XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMVS_GET_PRICES_FOR_SP_INPUT[] IT_INPUT { get; set; }
    }

    [XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMVS_GET_PRICES_FOR_SP_INPUT
    {
        [XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string LIFNR { get; set; }

        [XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string WERKS { get; set; }

        [XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=2)]
        public string MATNR { get; set; }

        [XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=3)]
        public string ZDATE { get; set; }
    }

    [XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMVS_GET_PRICES_FOR_SP_OUTPUT
    {
        [XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=0)]
        public string LIFNR{ get; set; }

        [XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=1)]
        public string WERKS { get; set; }

        [XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=2)]
        public string MATNR { get; set; }

        [XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=3)]
        public string ZDATE { get; set; }

        [XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=4)]
        public decimal KBETR { get; set; }

        [XmlElementAttribute(Form=XmlSchemaForm.Unqualified, Order=5)]
        public string CN_NDS { get; set; }
    }

    [XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZMV_WS_GET_PRICES_FOR_SPResponse
    {
        [XmlArrayAttribute(Form=XmlSchemaForm.Unqualified, Order=0)]
        [XmlArrayItemAttribute("item", Form=XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZMVS_GET_PRICES_FOR_SP_OUTPUT[] ET_OUTPUT { get; set; }
    }

    [MessageContractAttribute(IsWrapped=false)]
    public partial class ZMV_WS_GET_PRICES_FOR_SPRequest
    {
        [MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public ZMV_WS_GET_PRICES_FOR_SP1 ZMV_WS_GET_PRICES_FOR_SP;

        public ZMV_WS_GET_PRICES_FOR_SPRequest()
        {
        }

        public ZMV_WS_GET_PRICES_FOR_SPRequest(ZMV_WS_GET_PRICES_FOR_SP1 ZMV_WS_GET_PRICES_FOR_SP)
        {
            this.ZMV_WS_GET_PRICES_FOR_SP = ZMV_WS_GET_PRICES_FOR_SP;
        }
    }

    [MessageContractAttribute(IsWrapped=false)]
    public partial class ZMV_WS_GET_PRICES_FOR_SPResponse1
    {
        [MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public ZMV_WS_GET_PRICES_FOR_SPResponse ZMV_WS_GET_PRICES_FOR_SPResponse;

        public ZMV_WS_GET_PRICES_FOR_SPResponse1()
        {
        }

        public ZMV_WS_GET_PRICES_FOR_SPResponse1(ZMV_WS_GET_PRICES_FOR_SPResponse ZMV_WS_GET_PRICES_FOR_SPResponse)
        {
            this.ZMV_WS_GET_PRICES_FOR_SPResponse = ZMV_WS_GET_PRICES_FOR_SPResponse;
        }
    }

    public partial class ZMV_WS_GET_PRICES_FOR_SPClient : ClientBase<ZMV_WS_GET_PRICES_FOR_SP>, ZMV_WS_GET_PRICES_FOR_SP
    {
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(ServiceEndpoint serviceEndpoint, ClientCredentials clientCredentials);

        public ZMV_WS_GET_PRICES_FOR_SPClient(Binding binding, EndpointAddress remoteAddress)
            : base(binding, remoteAddress)
        {
        }

        public Task<ZMV_WS_GET_PRICES_FOR_SPResponse1> ZMV_WS_GET_PRICES_FOR_SPAsync(ZMV_WS_GET_PRICES_FOR_SPRequest request)
        {
            return base.Channel.ZMV_WS_GET_PRICES_FOR_SPAsync(request);
        }
    }
}
